[project]
name = "code-search-mcp-server"
version = "0.1.0"
description = "FastMCP server that exposes a simple code search tool."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=2.3.4",
    "mcp[cli]>=1.9.0",
]

